### ISSUE TITLE
Empty Length

### ISSUE THREAD

**Issue by usermode** [vdisasm/InnoSetupDecompiler#4] opened 2016-12-26 15:44 UTC
script:
if Length(Pwd.Text) < 4  then

decompiler:
v_9 := gvar_16;
v_8 := v_9.TEXT;
v_7 := LENGTH();
v_6 := v_7 < 4;
flag := not v_6;

or
script:
MsgBox(IntToStr(Length('ImageList_AddMasked')), mbCriticalError, mb_OK);

decompiler:
v_2 := 0;
v_3 := 3;
v_7 := 'ImageList_AddMasked';
v_6 := LENGTH();
v_5 := v_6;
v_4 := INTTOSTR(v_5);
v_1 := MSGBOX(v_4, v_3, v_2);

**Comment by vdisasm** [comment] 2016-12-26 16:13
Related to issue #2.
Some functions (length, inc, dec and some other) have parameters declared at runtime.
I'm going to fix it this week.

**Comment by vdisasm** [comment] 2016-12-28 18:01
Closed as duplicate of #2.

**Closed by vdisasm** 2016-12-28 18:01 UTC
