### ISSUE TITLE
Empty value for array of char size

### ISSUE THREAD

**Issue by usermode** [vdisasm/InnoSetupDecompiler#8] opened 2016-12-27 22:38 UTC
script:
function DecToHex(Value: Integer): string; 
var
  HS: array of Char;
begin 
  HS := ['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'];
  Result := ''; 
  while Value > 0 do 
  begin 
    Result := HS[Value mod 16] + Result; 
    Value := Value shr 4; 
  end; 
end; 

decompiler:
v_3 := 16;
SETARRAYLENGTH(); // must be v_3
v_2.0 := '0';
v_2.1 := '1';
v_2.2 := '2';
v_2.3 := '3';
v_2.4 := '4';
v_2.5 := '5';
v_2.6 := '6';
v_2.7 := '7';
v_2.8 := '8';
v_2.9 := '9';
v_2.10 := 'A';
v_2.11 := 'B';
v_2.12 := 'C';
v_2.13 := 'D';
v_2.14 := 'E';
v_2.15 := 'F';
v_1 := v_2;
result := '';
//cut

**Comment by vdisasm** [comment] 2016-12-28 14:08
Related to #2

**Comment by vdisasm** [comment] 2016-12-28 18:02
Closed as duplicate of #2.

**Closed by vdisasm** 2016-12-28 18:02 UTC
